spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jspexer
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false
  jdbc:
    template:
      query-timeout: 3
mybatis:
  mapper-locations: classpath:mybatis/com.atguigu.admin.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true